# Generated by Django 4.2 on 2026-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('L', 'Lagartija'), ('P', 'Planta'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('T', 'Tierra')], max_length=30),
        ),
    ]
