# Generated by Django 5.2 on 2026-06-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('L', 'Lagartija'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('P', 'Planta')], max_length=30),
        ),
    ]
