# Generated by Django 5.2 on 2026-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('A', 'Agua'), ('T', 'Tierra'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('P', 'Planta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
