# Generated by Django 5.2 on 2026-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_height_alter_pokemon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
