# Generated by Django 5.2 on 2026-06-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('E', 'Eléctrico'), ('A', 'Agua'), ('P', 'Planta'), ('F', 'Fuego'), ('T', 'Tierra')], max_length=30),
        ),
    ]
