# Generated by Django 5.2 on 2026-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('F', 'Fuego'), ('A', 'Agua'), ('T', 'Tierra'), ('L', 'Lagartija'), ('P', 'Planta')], max_length=30),
        ),
    ]
